{
 "title": "icon-network-dashboard-1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "network_name", "label": "network_name", "query": "mainnet,testnet,zicon,bicon" }
  ]
 },
 "panels": [
  {
   "title": "Active Main P-Reps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_total_active_main_preps{network_name=\"$network_name\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Active Sub P-Reps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_total_active_sub_preps{network_name=\"$network_name\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Inactive Sub P-Reps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_total_inactive_sub_preps{network_name=\"$network_name\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Block Time (s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_prep_reference_block_time{network_name=\"$network_name\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_prep_reference_block_height{network_name=\"$network_name\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_total_tx{network_name=\"$network_name\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Active Main P-Reps vs Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "icon_total_active_main_preps{network_name=\"$network_name\"}"
    }
   ]
  },
  {
   "title": "Total Number of Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "icon_total_tx{network_name=\"$network_name\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Active Sub P-Reps vs Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "icon_total_active_sub_preps{network_name=\"$network_name\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Block Height vs Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "icon_prep_reference_block_height{network_name=\"$network_name\"}",
     "legendFormat": " "
    }
   ]
  }
 ]
}