{
 "title": "single-node-details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network_name", "label": "network_name", "query": "mainnet,zicon,bicon,testnet" },
   {
    "name": "team",
    "label": "team",
    "query": "icon_prep_node_rank{network_name=\"$network_name\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "icon_prep_node_block_height{name=\"$team\",network_name=\"$network_name\"}",
     "legendFormat": "$team"
    },
    {
     "expr": "icon_prep_reference_block_height{network_name=\"$network_name\"}",
     "legendFormat": "Reference"
    }
   ]
  },
  {
   "title": "Blocks Left in Term",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "icon_blocks_left_in_term{network_name=\"$network_name\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "icon_prep_node_block_time{name=\"$team\",network_name=\"$network_name\"}",
     "legendFormat": "$team"
    },
    {
     "expr": "icon_prep_reference_block_time{network_name=\"$network_name\"}",
     "legendFormat": "Reference"
    }
   ]
  },
  {
   "title": "Node State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "icon_prep_node_state{name=\"$team\",network_name=\"$network_name\"}",
     "legendFormat": "$team"
    }
   ]
  }
 ]
}